### PR TITLE
Feature/centos7 ruby

### PR DESCRIPTION
**Pull request by cramaker**
This up's the ruby version to 2.0 for Redhat/CentOS 7 and uses gems to install bundler (there isn't a native RPM package)

This has been tested on CentOS 7.2 

There is also a .kitchen.yml file to allow easy testing the test kitchen

### CODE REVIEW

**Comment by gravyboat** [comment]
Hmm, I merged this in but now that I think about it, won't this create an issue for old Cent/RedHat releases?

**Comment by cramaker** [comment]
@gravyboat That's a good point - I can cut another branch and add some logic in there to make it backwards-compatible with CentOS 6. I plan on doing some more work to get rvm polished up.

**Comment by gravyboat** [comment]
@cramaker Yeah if you could that would be great. If you can keep that PR separate from the RVM one that would be good as well. I'm sure someone will be around shortly to complain about how this broke Ruby on their centos 5 server.

**Comment by cramaker** [comment]
@gravyboat Running through the tests on these...was there a particular reason that you chose ruby193 for the Redhat builds? I checked out the commit prior to my work and ran it against both CentOS 5 & 6 and it had issues installing all three packages.

If there isn't a hard dependency on that particular version/package and if it isn't going to impact anybody else's work, I think we're good here since they didn't work before my changes. 

Please let me know your thoughts.

**Comment by gravyboat** [comment]
@cramaker I really don't remember (I haven't personally committed anything to this repo, I just merge stuff in usually). It looks like this was added back in 2015 when the formula was reworked https://github.com/saltstack-formulas/ruby-formula/pull/7 so I'm fine with it if it works on CentOS 5 and 6 with the new changes.

**Pull request merged**
